/* AUTO-GENERATED by tools/gen_schema.py from the accepted contract's
 * schemas.json. Do not hand-edit; regenerate instead. */
#pragma once
#include <stdint.h>

typedef struct { uint8_t b[6]; } mtk_mac6_t;
typedef struct { uint8_t b[4]; } mtk_ipv4_t;

typedef struct {
    mtk_mac6_t bssid;
    struct { uint16_t len; uint8_t data[32]; } ssid;
    uint8_t channel;
    int8_t rssi;
    uint8_t authmode;
} mtk_aprecord_t;

typedef struct {
    mtk_mac6_t mac;
    int8_t rssi;
} mtk_stationrecord_t;

typedef struct {
    uint8_t mode;
    uint8_t channel;
    uint8_t band;
    uint16_t hop_dwell_ms;
} mtk_channelplan_t;

typedef struct {
    mtk_mac6_t filter_bssid;
} mtk_capturefilter_t;

typedef struct {
    uint8_t mode;
    mtk_ipv4_t static_ip;
    mtk_ipv4_t static_netmask;
    mtk_ipv4_t static_gateway;
    mtk_ipv4_t static_dns;
} mtk_ipconfig_t;

typedef struct {
    uint8_t kind;
    struct { uint16_t len; uint8_t data[64]; } psk;
} mtk_credential_t;

typedef struct {
    uint8_t width;
    uint8_t value[16];
} mtk_uuid_t;

typedef struct {
    mtk_mac6_t addr;
    uint8_t addr_type;
} mtk_bleaddress_t;

typedef struct {
    struct { uint16_t len; uint8_t data[32]; } ssid;
    struct { uint16_t len; uint8_t data[64]; } psk;
    uint8_t channel;
} mtk_softapconfig_t;

typedef struct {
    uint32_t nonce;
} mtk_ping_req_t;

typedef struct {
    uint32_t nonce;
} mtk_ping_resp_t;

typedef struct {
    uint16_t service_id;
    uint8_t service_major;
    uint8_t service_minor;
} mtk_anon_mtk_get_version_resp_t_service_summary_elem_1_t;

typedef struct {
    uint8_t product_major;
    uint8_t product_minor;
    uint8_t product_patch;
    struct { uint16_t len; uint8_t data[40]; } build_id;
    uint8_t build_dirty;
    uint32_t build_epoch_s;
    uint8_t build_epoch_reproducible;
    uint8_t target_chip;
    struct { uint16_t len; uint8_t data[24]; } hw_compat_id;
    struct { uint16_t len; uint8_t data[32]; } esp_idf_version;
    uint8_t protocol_major;
    uint8_t protocol_minor;
    struct { uint32_t count; mtk_anon_mtk_get_version_resp_t_service_summary_elem_1_t items[8]; } service_summary;
} mtk_get_version_resp_t;

typedef struct {
    uint8_t max_inflight_requests;
    uint8_t max_reassembly_contexts;
    uint32_t max_control_payload;
    uint8_t max_operation_tokens;
    uint8_t max_terminal_event_reserve;
    uint8_t max_progress_event_queue;
    uint8_t max_cursors;
    uint8_t max_owned_buffers;
    uint32_t operation_record_retention_ms;
} mtk_get_limits_resp_t;

typedef struct {
    uint16_t start_index;
    uint8_t max_items;
} mtk_get_capabilities_req_t;

typedef struct {
    uint16_t service_id;
    uint16_t opcode;
    uint16_t capability_id;
    uint8_t service_major;
    uint8_t service_minor;
    uint8_t state;
    uint8_t max_concurrent;
    uint16_t max_payload;
    struct { uint32_t count; uint16_t items[4]; } dependencies;
} mtk_anon_mtk_get_capabilities_resp_t_entries_elem_2_t;

typedef struct {
    struct { uint32_t count; mtk_anon_mtk_get_capabilities_resp_t_entries_elem_2_t items[32]; } entries;
    uint16_t next_index;
} mtk_get_capabilities_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_get_operation_status_req_t;

typedef struct {
    uint8_t state;
    uint16_t owning_service_id;
    uint16_t owning_operation;
    uint32_t elapsed_ms;
} mtk_get_operation_status_resp_t;

typedef struct {
    uint32_t delay_ms;
} mtk_reset_intent_req_t;

typedef struct {
    uint32_t accepted_delay_ms;
} mtk_reset_intent_resp_t;

typedef struct {
    uint32_t operation_token;
    uint32_t fires_at_boot_ms;
} mtk_reset_scheduled_ev_t;

typedef struct {
    uint8_t reason;
} mtk_get_reset_reason_resp_t;

typedef struct {
    struct { uint16_t len; uint8_t data[253]; } server;
    uint32_t timeout_ms;
} mtk_time_sync_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_time_sync_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    uint64_t unix_time_ms;
    uint8_t stratum;
    uint32_t uncertainty_ms;
} mtk_time_sync_result_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_time_sync_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_time_sync_stop_resp_t;

typedef struct {
    uint8_t band;
    mtk_channelplan_t channel_plan;
} mtk_ap_scan_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_ap_scan_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint16_t found_so_far;
    uint16_t visible_drop_count;
} mtk_ap_scan_progress_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    uint32_t result_generation;
    uint16_t result_count;
} mtk_ap_scan_complete_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_ap_scan_status_req_t;

typedef struct {
    uint8_t state;
    uint16_t found_so_far;
} mtk_ap_scan_status_resp_t;

typedef struct {
    uint32_t result_generation;
    uint32_t start_index;
    uint8_t max_items;
} mtk_ap_scan_results_page_req_t;

typedef struct {
    struct { uint32_t count; mtk_aprecord_t items[50]; } items;
    uint32_t next_index;
} mtk_ap_scan_results_page_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_ap_scan_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_ap_scan_stop_resp_t;

typedef struct {
    uint32_t result_generation;
    uint16_t index;
} mtk_ap_details_req_t;

typedef struct {
    mtk_aprecord_t record;
} mtk_ap_details_resp_t;

typedef struct {
    mtk_mac6_t target_bssid;
    uint8_t channel;
    uint16_t duration_ms;
} mtk_sta_scan_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_sta_scan_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    uint32_t result_generation;
    uint16_t result_count;
} mtk_sta_scan_complete_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_sta_scan_status_req_t;

typedef struct {
    uint8_t state;
    uint16_t found_so_far;
} mtk_sta_scan_status_resp_t;

typedef struct {
    uint32_t result_generation;
    uint32_t start_index;
    uint8_t max_items;
} mtk_sta_scan_results_page_req_t;

typedef struct {
    struct { uint32_t count; mtk_stationrecord_t items[32]; } items;
    uint32_t next_index;
} mtk_sta_scan_results_page_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_sta_scan_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_sta_scan_stop_resp_t;

typedef struct {
    struct { uint16_t len; uint8_t data[32]; } ssid;
    mtk_mac6_t bssid_hint;
    uint8_t channel_hint;
    uint8_t auth_mode;
    mtk_credential_t credential;
    mtk_ipconfig_t ip_config;
    uint8_t persistence;
    uint32_t connect_timeout_ms;
} mtk_sta_connect_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_sta_connect_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    mtk_mac6_t bssid;
    uint8_t channel;
    uint8_t ip_present;
    mtk_ipv4_t ip_addr;
} mtk_sta_connect_complete_ev_t;

typedef struct {
    uint8_t reason_class;
    uint16_t disconnect_reason_code;
} mtk_sta_connection_lost_ev_t;

typedef struct {
    uint8_t connected;
    struct { uint16_t len; uint8_t data[32]; } ssid;
    mtk_mac6_t bssid;
    uint8_t channel;
    uint8_t ip_present;
    mtk_ipv4_t ip_addr;
    int8_t rssi;
} mtk_sta_status_resp_t;

typedef struct { uint16_t len; uint8_t data[32]; } mtk_bytes32_t;

typedef struct {
    struct { uint32_t count; mtk_bytes32_t items[32]; } ssids;
} mtk_beacon_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_beacon_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t channels_active_count;
    uint16_t visible_drop_count;
} mtk_beacon_status_event_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
} mtk_beacon_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_beacon_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_beacon_stop_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_beacon_status_req_t;

typedef struct {
    uint8_t state;
    uint8_t channels_active_count;
} mtk_beacon_status_resp_t;

typedef struct {
    uint8_t target_mode;
    uint32_t station_scan_token;
    mtk_mac6_t ap_bssid;
    uint8_t channel;
    struct { uint32_t count; mtk_mac6_t items[64]; } targets;
    uint16_t count;
    uint16_t interval_ms;
} mtk_deauth_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_deauth_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint16_t packets_per_second;
    uint16_t visible_drop_count;
} mtk_deauth_progress_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    uint32_t total_sent;
} mtk_deauth_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_deauth_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_deauth_stop_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_deauth_status_req_t;

typedef struct {
    uint8_t state;
    uint32_t sent;
} mtk_deauth_status_resp_t;

typedef struct {
    mtk_mac6_t target_bssid;
    uint8_t channel;
    uint16_t deauth_count;
} mtk_handshake_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_handshake_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t phase;
    uint8_t key_frame;
    uint16_t visible_drop_count;
} mtk_handshake_event_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    uint32_t captured_total_len;
} mtk_handshake_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_handshake_status_req_t;

typedef struct {
    uint8_t state;
    uint32_t total_len;
} mtk_handshake_status_resp_t;

typedef struct {
    uint32_t operation_token;
    uint32_t offset;
    uint16_t max_len;
} mtk_handshake_read_req_t;

typedef struct {
    struct { uint16_t len; uint8_t data[512]; } data;
    uint32_t total_len;
} mtk_handshake_read_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_handshake_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_handshake_stop_resp_t;

typedef struct {
    struct { uint32_t count; uint32_t items[8]; } stopped_operations;
} mtk_wifi_stop_all_resp_t;

typedef struct {
    uint8_t radio_owner;
    uint8_t active_operation_count;
    uint8_t sta_mode_restored;
} mtk_get_wifi_recovery_state_resp_t;

typedef struct {
    mtk_softapconfig_t config;
} mtk_softap_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_softap_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t actual_channel;
} mtk_softap_ready_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
} mtk_softap_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_softap_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_softap_stop_resp_t;

typedef struct {
    uint8_t active;
    uint8_t connected_station_count;
    uint8_t internet_shared;
} mtk_softap_sta_list_resp_t;

typedef struct {
    uint8_t channel;
    struct { uint32_t count; mtk_bytes32_t items[16]; } ssids;
} mtk_probe_flood_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_probe_flood_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint32_t probes_sent;
    uint16_t visible_drop_count;
} mtk_probe_flood_progress_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
} mtk_probe_flood_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_probe_flood_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_probe_flood_stop_resp_t;

typedef struct {
    mtk_mac6_t target_bssid;
    uint8_t channel;
} mtk_pmkid_capture_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_pmkid_capture_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    uint8_t pmkid_present;
    uint8_t pmkid[16];
} mtk_pmkid_capture_result_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_pmkid_capture_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_pmkid_capture_stop_resp_t;

typedef struct {
    uint8_t channel;
} mtk_karma_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_karma_start_resp_t;

typedef struct {
    uint32_t operation_token;
    mtk_mac6_t requesting_client;
    struct { uint16_t len; uint8_t data[32]; } probed_ssid;
    uint16_t visible_drop_count;
} mtk_karma_probe_seen_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
} mtk_karma_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_karma_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_karma_stop_resp_t;

typedef struct {
    uint8_t channel;
    struct { uint16_t len; uint8_t data[1489]; } frame;
} mtk_raw_tx_send_req_t;

typedef struct {
    struct { uint16_t len; uint8_t data[32]; } ssid;
    uint8_t channel;
    struct { uint16_t len; uint8_t data[95]; } portal_title;
} mtk_captive_portal_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_captive_portal_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t actual_channel;
} mtk_captive_portal_ready_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
} mtk_captive_portal_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_captive_portal_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_captive_portal_stop_resp_t;

typedef struct {
    uint8_t max_count;
} mtk_captive_portal_get_credentials_req_t;

typedef struct {
    uint32_t captured_at_epoch_s;
    struct { uint16_t len; uint8_t data[64]; } username;
    struct { uint16_t len; uint8_t data[64]; } password;
} mtk_anon_mtk_captive_portal_get_credentials_resp_t_credentials_elem_3_t;

typedef struct {
    struct { uint32_t count; mtk_anon_mtk_captive_portal_get_credentials_resp_t_credentials_elem_3_t items[32]; } credentials;
} mtk_captive_portal_get_credentials_resp_t;

typedef struct {
    uint32_t dns_queries;
    uint32_t http_hits;
    uint8_t connected_clients;
    struct { uint16_t len; uint8_t data[95]; } last_post_body;
} mtk_captive_portal_get_diagnostics_resp_t;

typedef struct {
    uint8_t baseline_mode;
    uint8_t effective_mode;
} mtk_wifi_mode_get_resp_t;

typedef struct {
    uint8_t mode;
} mtk_wifi_mode_set_req_t;

typedef struct {
    uint8_t previous_mode;
    uint8_t applied_mode;
} mtk_wifi_mode_set_resp_t;

typedef struct {
    uint8_t iface;
} mtk_wifi_mac_get_req_t;

typedef struct {
    mtk_mac6_t mac;
} mtk_wifi_mac_get_resp_t;

typedef struct {
    uint8_t mode;
    uint16_t duration_ms;
    struct { uint16_t len; uint8_t data[32]; } name_filter;
} mtk_ble_scan_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_scan_start_resp_t;

typedef struct {
    uint32_t operation_token;
    mtk_mac6_t addr;
    uint8_t addr_type;
    int8_t rssi;
    struct { uint16_t len; uint8_t data[32]; } name;
    uint16_t visible_drop_count;
} mtk_ble_device_found_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    uint32_t result_generation;
    uint16_t result_count;
} mtk_ble_scan_complete_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_scan_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_ble_scan_stop_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_scan_status_req_t;

typedef struct {
    uint8_t state;
    uint16_t found_so_far;
} mtk_ble_scan_status_resp_t;

typedef struct {
    uint32_t result_generation;
    uint32_t start_index;
    uint8_t max_items;
} mtk_ble_scan_results_page_req_t;

typedef struct {
    mtk_mac6_t addr;
    uint8_t addr_type;
    int8_t rssi;
    struct { uint16_t len; uint8_t data[32]; } name;
} mtk_anon_mtk_ble_scan_results_page_resp_t_items_elem_4_t;

typedef struct {
    struct { uint32_t count; mtk_anon_mtk_ble_scan_results_page_resp_t_items_elem_4_t items[40]; } items;
    uint32_t next_index;
} mtk_ble_scan_results_page_resp_t;

typedef struct {
    uint32_t result_generation;
    uint8_t index;
} mtk_ble_device_details_req_t;

typedef struct {
    mtk_mac6_t addr;
    uint8_t addr_type;
    int8_t rssi;
    uint8_t adv_type;
    uint8_t flags;
    struct { uint16_t len; uint8_t data[32]; } name;
    int8_t tx_power;
    struct { uint16_t len; uint8_t data[31]; } mfg_data;
    struct { uint16_t len; uint8_t data[31]; } raw_adv;
    struct { uint16_t len; uint8_t data[31]; } raw_scan_rsp;
} mtk_ble_device_details_resp_t;

typedef struct {
    struct { uint16_t len; uint8_t data[31]; } name;
} mtk_ble_adv_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_adv_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
} mtk_ble_adv_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_adv_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_ble_adv_stop_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_adv_status_req_t;

typedef struct {
    uint8_t state;
    struct { uint16_t len; uint8_t data[31]; } name;
    uint8_t connectable;
    uint8_t has_scan_response;
} mtk_ble_adv_status_resp_t;

typedef struct {
    mtk_bleaddress_t target;
} mtk_signal_meter_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_signal_meter_start_resp_t;

typedef struct {
    uint32_t operation_token;
    int8_t raw_rssi;
    int8_t avg_rssi;
    uint8_t category;
    uint16_t age_ms;
    uint8_t is_random_address;
    uint16_t visible_drop_count;
} mtk_signal_meter_update_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
} mtk_signal_meter_lost_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_signal_meter_status_req_t;

typedef struct {
    uint8_t state;
    uint8_t is_random_address;
} mtk_signal_meter_status_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_signal_meter_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_signal_meter_stop_resp_t;

typedef struct {
    struct { uint16_t len; uint8_t data[31]; } name;
} mtk_ble_hid_init_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_hid_init_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t connected;
    uint8_t ready;
    uint16_t visible_drop_count;
} mtk_ble_hid_event_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
} mtk_ble_hid_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t modifier;
    struct { uint32_t count; uint8_t items[6]; } keys;
} mtk_ble_hid_key_req_t;

typedef struct {
    uint32_t operation_token;
    struct { uint16_t len; uint8_t data[502]; } text;
} mtk_ble_hid_string_req_t;

typedef struct {
    uint32_t operation_token;
    struct { uint16_t len; uint8_t data[502]; } script;
} mtk_ble_hid_script_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_hid_deinit_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_ble_hid_deinit_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_hid_status_req_t;

typedef struct {
    uint8_t connected;
    uint8_t ready;
} mtk_ble_hid_status_resp_t;

typedef struct {
    uint8_t mode;
} mtk_ble_spam_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_spam_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
} mtk_ble_spam_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_spam_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_ble_spam_stop_resp_t;

typedef struct {
    uint8_t beacon_type;
    uint8_t uuid[16];
    uint16_t major;
    uint16_t minor;
    int8_t tx_power;
    struct { uint16_t len; uint8_t data[79]; } eddystone_url;
} mtk_ble_compat_beacon_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_compat_beacon_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
} mtk_ble_compat_beacon_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_ble_compat_beacon_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_ble_compat_beacon_stop_resp_t;

typedef struct {
    uint8_t enable;
    struct { uint16_t len; uint8_t data[31]; } name;
} mtk_ble_direct_adv_set_req_t;

typedef struct {
    uint8_t direct_advertising;
    uint8_t direct_connected;
    uint8_t hid_advertising;
    uint8_t hid_connected;
    int8_t last_hid_adv_result_code;
} mtk_ble_compat_state_resp_t;

typedef struct {
    mtk_bleaddress_t target;
} mtk_gatt_connect_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_gatt_connect_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    uint32_t connection_token;
} mtk_gatt_connect_complete_ev_t;

typedef struct {
    uint32_t connection_token;
} mtk_gatt_disconnect_req_t;

typedef struct {
    uint32_t connection_token;
} mtk_gatt_status_req_t;

typedef struct {
    uint8_t connected;
    uint32_t dropped_notification_count;
    uint8_t write_pending;
} mtk_gatt_status_resp_t;

typedef struct {
    uint32_t connection_token;
    uint16_t start_index;
    uint8_t max_items;
} mtk_gatt_discover_req_t;

typedef struct {
    mtk_uuid_t uuid;
    uint16_t start_handle;
    uint16_t end_handle;
} mtk_anon_mtk_gatt_discover_resp_t_services_elem_5_t;

typedef struct {
    struct { uint32_t count; mtk_anon_mtk_gatt_discover_resp_t_services_elem_5_t items[16]; } services;
    uint16_t next_index;
} mtk_gatt_discover_resp_t;

typedef struct {
    uint32_t connection_token;
    uint16_t handle;
} mtk_gatt_read_req_t;

typedef struct {
    struct { uint16_t len; uint8_t data[512]; } data;
} mtk_gatt_read_resp_t;

typedef struct {
    uint32_t connection_token;
    uint16_t handle;
    struct { uint16_t len; uint8_t data[64]; } data;
    uint8_t with_response;
} mtk_gatt_write_req_t;

typedef struct {
    uint32_t connection_token;
    uint16_t handle;
    uint8_t mode;
} mtk_gatt_subscribe_req_t;

typedef struct {
    uint32_t connection_token;
    uint16_t handle;
    uint8_t mode;
    struct { uint16_t len; uint8_t data[32]; } data;
} mtk_gatt_value_event_ev_t;

typedef struct {
    uint32_t connection_token;
    uint32_t dropped_count;
} mtk_gatt_drop_event_ev_t;

typedef struct {
    uint32_t connection_token;
    uint16_t handle;
} mtk_gatt_unsubscribe_req_t;

typedef struct {
    uint8_t mode;
    uint16_t snap_len;
    uint32_t duration_ms;
    mtk_channelplan_t channel_plan;
    mtk_capturefilter_t filter;
} mtk_capture_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_capture_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t channel;
    uint16_t visible_drop_count;
} mtk_capture_channel_event_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    uint8_t reason;
    uint32_t total_frames;
    uint32_t dropped_frames;
    uint32_t truncated_frames;
} mtk_capture_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
    uint8_t reason;
} mtk_capture_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
    uint8_t final_reason;
} mtk_capture_stop_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_capture_status_req_t;

typedef struct {
    uint8_t state;
    uint8_t mode;
    uint32_t frames_captured;
    uint32_t frames_dropped;
    uint8_t buffered;
} mtk_capture_status_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_capture_session_info_req_t;

typedef struct {
    uint32_t session_id;
    uint8_t mode;
    uint16_t snap_len;
    mtk_channelplan_t channel_plan;
    mtk_capturefilter_t filter;
    uint64_t started_at_boot_us;
} mtk_capture_session_info_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_capture_stats_req_t;

typedef struct {
    uint32_t total_frames;
    uint32_t dropped_frames;
    uint32_t truncated_frames;
    uint32_t credit_stalls;
} mtk_capture_stats_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_capture_poll_read_req_t;

typedef struct {
    uint32_t integrity_failures;
    uint32_t dropped_frames;
    uint32_t packet_seq_gaps;
    uint32_t retries_observed;
    uint32_t duplicate_responses_served;
} mtk_get_transport_counters_resp_t;

typedef struct {
    uint8_t wifi_owner_class;
    uint8_t ble_owner_class;
    struct { uint32_t count; uint32_t items[8]; } active_operation_tokens;
} mtk_get_radio_resource_state_resp_t;

typedef struct {
    uint8_t control_queue_high_water;
    uint8_t event_queue_high_water;
    uint8_t cursor_high_water;
    uint8_t owned_buffer_high_water;
    uint8_t capture_ring_high_water_pct;
    uint32_t heap_free_bytes;
    uint32_t heap_min_free_bytes;
} mtk_get_queue_watermarks_resp_t;

typedef struct {
    uint8_t last_reset_reason;
    uint8_t fault_class;
    uint8_t redacted;
} mtk_get_fault_summary_resp_t;

typedef struct {
    uint32_t connection_token;
    uint16_t start_handle;
    uint16_t end_handle;
    uint16_t start_index;
    uint8_t max_items;
} mtk_gatt_discover_chars_req_t;

typedef struct {
    mtk_uuid_t uuid;
    uint16_t def_handle;
    uint16_t val_handle;
    uint8_t properties;
} mtk_anon_mtk_gatt_discover_chars_resp_t_items_elem_6_t;

typedef struct {
    struct { uint32_t count; mtk_anon_mtk_gatt_discover_chars_resp_t_items_elem_6_t items[16]; } items;
    uint16_t next_index;
} mtk_gatt_discover_chars_resp_t;

typedef struct {
    uint32_t connection_token;
    uint16_t start_handle;
    uint16_t end_handle;
    uint16_t start_index;
    uint8_t max_items;
} mtk_gatt_discover_descs_req_t;

typedef struct {
    mtk_uuid_t uuid;
    uint16_t handle;
} mtk_anon_mtk_gatt_discover_descs_resp_t_items_elem_7_t;

typedef struct {
    struct { uint32_t count; mtk_anon_mtk_gatt_discover_descs_resp_t_items_elem_7_t items[16]; } items;
    uint16_t next_index;
} mtk_gatt_discover_descs_resp_t;

typedef struct {
    uint8_t channel;
} mtk_espnow_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_espnow_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    uint32_t sent_ok;
    uint32_t received;
} mtk_espnow_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_espnow_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_espnow_stop_resp_t;

typedef struct {
    mtk_mac6_t peer;
    uint8_t channel;
    uint8_t encrypt;
    struct { uint16_t len; uint8_t data[16]; } lmk;
} mtk_espnow_add_peer_req_t;

typedef struct {
    mtk_mac6_t peer;
    struct { uint16_t len; uint8_t data[250]; } data;
} mtk_espnow_send_req_t;

typedef struct {
    uint32_t sent_ok;
    uint32_t send_fail;
    uint32_t received;
    uint32_t dropped;
} mtk_espnow_stats_resp_t;

typedef struct {
    uint8_t channel;
    uint8_t promiscuous;
} mtk_ieee154_start_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_ieee154_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    uint32_t frames_received;
    uint32_t frames_dropped;
} mtk_ieee154_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_ieee154_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_ieee154_stop_resp_t;

typedef struct {
    uint8_t state;
    uint8_t channel;
    uint8_t promiscuous;
    uint32_t frames_received;
    uint32_t frames_dropped;
    uint32_t frames_transmitted;
    uint32_t tx_failures;
} mtk_ieee154_status_resp_t;

typedef struct {
    uint8_t channel;
} mtk_ieee154_set_channel_req_t;

typedef struct {
    uint32_t channel_mask;
    uint16_t dwell_ms;
} mtk_ieee154_energy_scan_req_t;

typedef struct {
    uint32_t operation_token;
} mtk_ieee154_energy_scan_resp_t;

typedef struct {
    uint8_t channel;
    int8_t peak_rssi;
} mtk_anon_mtk_ieee154_energy_result_ev_t_results_elem_8_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
    struct { uint32_t count; mtk_anon_mtk_ieee154_energy_result_ev_t_results_elem_8_t items[16]; } results;
} mtk_ieee154_energy_result_ev_t;

typedef struct {
    struct { uint16_t len; uint8_t data[127]; } data;
    uint8_t cca;
} mtk_ieee154_tx_req_t;

typedef struct {
    uint8_t tx_status;
} mtk_ieee154_tx_resp_t;

typedef struct {
    uint32_t operation_token;
} mtk_ieee154_rcp_start_resp_t;

typedef struct {
    uint32_t operation_token;
    uint8_t status;
} mtk_ieee154_rcp_stopped_ev_t;

typedef struct {
    uint32_t operation_token;
} mtk_ieee154_rcp_stop_req_t;

typedef struct {
    uint8_t final_state;
    uint8_t final_status;
} mtk_ieee154_rcp_stop_resp_t;

typedef struct {
    uint8_t running;
    uint8_t host_link;
    uint32_t baud_rate;
} mtk_ieee154_rcp_status_resp_t;
