#!/usr/bin/env python3
"""Generate the Legacy SPI Compatibility wire-opcode to canonical-opcode table
from schemas.json's `adapter_map.compat_spi` field.

The generated lookup table is compiled into the compatibility adapter. Keeping
it generated makes the schema the single source of truth for opcode mappings.

Usage: gen_compat_map.py --schema <path-to-schemas.json> --out <components/mtek_transport_spi_compat-dir>
"""
import argparse
import json
import os
import re


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    schema = json.load(open(args.schema))

    rows = []
    for op in schema["opcodes"]:
        b = op.get("adapter_map", {}).get("compat_spi")
        if not b:
            continue
        m = re.match(r"^(0x[0-9A-Fa-f]{4})", b)
        if not m:
            continue
        rows.append((m.group(1), op["service"], op["opcode"], op["name"]))

    lines = [
        "/* AUTO-GENERATED by tools/gen_compat_map.py from schemas.json adapter_map.compat_spi.",
        " * Do not hand-edit; regenerate instead. */",
        '#include "mtek_compat_opcode_map.h"',
        "",
        f"const mtk_compat_opcode_row_t mtk_compat_opcode_table[{len(rows)}] = {{",
    ]
    for wire, svc, opc, name in rows:
        lines.append(f'    {{ {wire}, {svc}, {opc}, "{name}" }},')
    lines.append("};")
    lines.append(f"const unsigned mtk_compat_opcode_table_count = {len(rows)};")

    os.makedirs(os.path.join(args.out, "generated"), exist_ok=True)
    with open(os.path.join(args.out, "generated", "mtek_compat_opcode_table.c"), "w") as f:
        f.write("\n".join(lines))
    print(f"Generated {len(rows)} Legacy SPI Compatibility opcode reference rows.")


if __name__ == "__main__":
    main()
