#!/usr/bin/env python3
"""Generates the Bedge/C3 wire-opcode -> canonical-opcode reference table
from the accepted contract's schemas.json `adapter_map.bedge_c3` field.

This is documentation/lookup data only -- see docs/PROVENANCE.md for why
the Bedge/C3 SPI adapter does not yet dispatch on-wire: the facts-only
contract package supplied for this task does not include the Bedge/C3 SPI
frame header's byte layout (magic/msg_id/opcode offsets), only its opcode
*values* and per-operation semantics (cited in prose from a source file
this task's clean-room boundary forbids opening directly). This table
exists so the mapping is traceable to schemas.json and reusable the moment
that missing fact is supplied.

Usage: gen_bedge_map.py --schema <path-to-schemas.json> --out <components/mtek_transport_spi_bedge-dir>
"""
import argparse
import json
import os
import re


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    schema = json.load(open(args.schema))

    rows = []
    for op in schema["opcodes"]:
        b = op.get("adapter_map", {}).get("bedge_c3")
        if not b:
            continue
        m = re.match(r"^(0x[0-9A-Fa-f]{4})", b)
        if not m:
            continue
        rows.append((m.group(1), op["service"], op["opcode"], op["name"]))

    lines = [
        "/* AUTO-GENERATED by tools/gen_bedge_map.py from schemas.json adapter_map.bedge_c3.",
        " * Do not hand-edit; regenerate instead. Reference/documentation data only --",
        " * see components/mtek_transport_spi_bedge/mtek_bedge_opcode_map.c for why this",
        " * is not yet wired to live SPI dispatch. */",
        '#include "mtek_bedge_opcode_map.h"',
        "",
        f"const mtk_bedge_opcode_row_t mtk_bedge_opcode_table[{len(rows)}] = {{",
    ]
    for wire, svc, opc, name in rows:
        lines.append(f'    {{ {wire}, {svc}, {opc}, "{name}" }},')
    lines.append("};")
    lines.append(f"const unsigned mtk_bedge_opcode_table_count = {len(rows)};")

    os.makedirs(os.path.join(args.out, "generated"), exist_ok=True)
    with open(os.path.join(args.out, "generated", "mtek_bedge_opcode_table.c"), "w") as f:
        f.write("\n".join(lines))
    print(f"Generated {len(rows)} Bedge/C3 opcode reference rows.")


if __name__ == "__main__":
    main()
